[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
        *.google.com
        *.googleapis.com 
        *.googletagmanager.com 
        *.google-analytics.com 
        *.doubleclick.net
        *.facebook.com 
        *.fbcdn.net 
        *.facebook.net 
        connect.facebook.net;
      style-src 'self' 'unsafe-inline' 
        *.googleapis.com 
        fonts.googleapis.com;
      font-src 'self' fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' 
        *.google-analytics.com 
        *.facebook.com 
        *.fbcdn.net;
      frame-src 'self' 
        *.facebook.com 
        *.doubleclick.net;
    """

[build]
  publish = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200