[build]
  command = "npm install && npm run build"
  publish = "projects/transaction-ticker/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"

[[redirects]]
  from = "/projects/transaction-ticker/*"
  to = "/projects/transaction-ticker/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      connect-src 'self' connect.squareup.com '/.netlify/functions/*';
    """