[build]
  command = "npm install && npm run build"
  publish = "/"  # or your actual build directory if you have one
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"

# If you need any redirects for your AB Development site, add them here
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      connect-src 'self';
    """