[build]
  base = "RN"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/RN/*"
  to = "/:splat"
  status = 200

[[headers]]
  for = "/RN/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"